### ISSUE TITLE
功能建议：希望增加一个倍速功能

### ISSUE THREAD

**Issue by LiteCoder** [pj567/TVMovie#1]
首先感谢作者开源TVMovie，继tv影院之后一直没有好用的点播软件
试用后各方面都还挺不错的，发现缺少刷剧刚需的倍速功能，希望增加一下

**Comment by pj567** [comment]
重构中



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月18日(星期四) 下午3:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [pj567/TVMovie] 功能建议：希望增加一个倍速功能 (#1)





 
首先感谢作者开源TVMovie，继tv影院之后一直没有好用的点播软件
 试用后各方面都还挺不错的，发现缺少刷剧刚需的倍速功能，希望增加一下

**Comment by LiteCoder** [comment]
收到，谢谢！
