### ISSUE TITLE
建议一下密码问题

### ISSUE THREAD

**Issue by wxfyes** [pj567/TVMovie#4]
能给特定源加入密码吗？这样用起来大人孩子就方便多了

**Comment by pj567** [comment]
自己观看的时候打开就是，自己看完了关闭这个源




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pj567/TVMovie"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月2日(星期五) 上午10:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[pj567/TVMovie] 建议一下密码问题 (#4)





 
能给特定源加入密码吗？这样用起来大人孩子就方便多了
