### ISSUE TITLE
搜索问题

### ISSUE THREAD

**Issue by wxfyes** [pj567/TVMovie#5]
远程手机扫码链接的问题，貌似不能正确获取本机ip地址，显示的跟你截图是一样的IP，扫码也是http://172.16.1.15:9978   望大佬看看

**Comment by pj567** [comment]
不支持模拟器




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pj567/TVMovie"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月2日(星期五) 中午11:08
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[pj567/TVMovie] 搜索问题 (#5)





 
远程手机扫码链接的问题，貌似不能正确获取本机ip地址，显示的跟你截图是一样的IP，扫码也是http://172.16.1.15:9978   望大佬看看

**Comment by wxfyes** [comment]
谢谢大佬回复，刚才测试了，电视很好！还有一个小小的建议，能不能把首页自动显示节目，比如电影

**Comment by pj567** [comment]
没懂




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月2日(星期五) 中午11:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pj567/TVMovie] 搜索问题 (#5)





 
谢谢大佬回复，刚才测试了，电视很好！还有一个小小的建议，能不能把首页自动显示节目，比如电影

**Comment by wxfyes** [comment]
就像老版那样，选定资源库后，首页直接显示影片
